var dir_6308bc39371c39a0e1fd8fd7d55ee928 =
[
    [ "anisotropic.h", "anisotropic_8h.html", "anisotropic_8h" ],
    [ "basis.h", "basis_8h.html", "basis_8h" ],
    [ "camm.h", "camm_8h.html", "camm_8h" ],
    [ "coordination.h", "coordination_8h.html", "coordination_8h" ],
    [ "cpcmx.h", "cpcmx_8h.html", "cpcmx_8h" ],
    [ "ewald_common.h", "ewald__common_8h.html", "ewald__common_8h" ],
    [ "gamma.h", "gamma_8h.html", "gamma_8h" ],
    [ "gfn2_engine.h", "gfn2__engine_8h.html", "gfn2__engine_8h" ],
    [ "gfn2_parameters.h", "gfn2__parameters_8h.html", "gfn2__parameters_8h" ],
    [ "gfn2_periodic_calculator.h", "gfn2__periodic__calculator_8h.html", "gfn2__periodic__calculator_8h" ],
    [ "h0.h", "h0_8h.html", "h0_8h" ],
    [ "h0_gradient.h", "h0__gradient_8h.html", "h0__gradient_8h" ],
    [ "kpoint_grid.h", "kpoint__grid_8h.html", "kpoint__grid_8h" ],
    [ "multipole_damping.h", "multipole__damping_8h.html", "multipole__damping_8h" ],
    [ "multipole_ewald.h", "multipole__ewald_8h.html", "multipole__ewald_8h" ],
    [ "multipole_ints.h", "multipole__ints_8h.html", "multipole__ints_8h" ],
    [ "periodic.h", "periodic_8h.html", "periodic_8h" ],
    [ "periodic_gamma.h", "periodic__gamma_8h.html", "periodic__gamma_8h" ],
    [ "periodic_integrals.h", "periodic__integrals_8h.html", "periodic__integrals_8h" ],
    [ "repulsion.h", "repulsion_8h.html", "repulsion_8h" ],
    [ "scc.h", "scc_8h.html", "scc_8h" ],
    [ "smd_xtb.h", "smd__xtb_8h.html", "smd__xtb_8h" ],
    [ "solvation_interface.h", "solvation__interface_8h.html", "solvation__interface_8h" ],
    [ "sto_ng.h", "sto__ng_8h.html", "sto__ng_8h" ],
    [ "tblite_wrapper.h", "tblite__wrapper_8h.html", "tblite__wrapper_8h" ],
    [ "xtb_calculator.h", "xtb__calculator_8h.html", "xtb__calculator_8h" ],
    [ "xtb_result.h", "xtb__result_8h.html", "xtb__result_8h" ],
    [ "xtb_wrapper.h", "xtb__wrapper_8h.html", "xtb__wrapper_8h" ]
];