var dir_eb006ca087d4b4837f6db1ad7c4b10da =
[
    [ "adaptive_grid.h", "adaptive__grid_8h.html", "adaptive__grid_8h" ],
    [ "basis_g94.h", "basis__g94_8h.html", "basis__g94_8h" ],
    [ "cifparser.h", "cifparser_8h.html", "cifparser_8h" ],
    [ "cifwriter.h", "cifwriter_8h.html", "cifwriter_8h" ],
    [ "conversion.h", "conversion_8h.html", "conversion_8h" ],
    [ "core_json.h", "core__json_8h.html", "core__json_8h" ],
    [ "crystal_json.h", "crystal__json_8h.html", "crystal__json_8h" ],
    [ "crystalgrower.h", "crystalgrower_8h.html", "crystalgrower_8h" ],
    [ "cube.h", "cube_8h.html", "cube_8h" ],
    [ "dftb_gen.h", "dftb__gen_8h.html", "dftb__gen_8h" ],
    [ "eigen_json.h", "eigen__json_8h.html", "eigen__json_8h" ],
    [ "engrad.h", "engrad_8h.html", "engrad_8h" ],
    [ "fchkreader.h", "fchkreader_8h.html", "fchkreader_8h" ],
    [ "fchkwriter.h", "fchkwriter_8h.html", "fchkwriter_8h" ],
    [ "gaussian_input_file.h", "gaussian__input__file_8h.html", "gaussian__input__file_8h" ],
    [ "gmf.h", "gmf_8h.html", "gmf_8h" ],
    [ "grid_settings.h", "grid__settings_8h.html", "grid__settings_8h" ],
    [ "isosurface_json.h", "isosurface__json_8h.html", "isosurface__json_8h" ],
    [ "json_basis.h", "json__basis_8h.html", "json__basis_8h" ],
    [ "kmcpp.h", "kmcpp_8h.html", "kmcpp_8h" ],
    [ "load_geometry.h", "load__geometry_8h.html", "load__geometry_8h" ],
    [ "moldenreader.h", "moldenreader_8h.html", "moldenreader_8h" ],
    [ "obj.h", "obj_8h.html", "obj_8h" ],
    [ "occ_input.h", "occ__input_8h.html", "occ__input_8h" ],
    [ "orca_json.h", "orca__json_8h.html", "orca__json_8h" ],
    [ "pc.h", "pc_8h.html", "pc_8h" ],
    [ "periodic_grid.h", "periodic__grid_8h.html", "periodic__grid_8h" ],
    [ "ply.h", "ply_8h.html", "ply_8h" ],
    [ "qcschema.h", "qcschema_8h.html", "qcschema_8h" ],
    [ "shelxfile.h", "shelxfile_8h.html", "shelxfile_8h" ],
    [ "solvent_json.h", "solvent__json_8h.html", "solvent__json_8h" ],
    [ "tinyply.h", "tinyply_8h.html", "tinyply_8h" ],
    [ "wavefunction_json.h", "wavefunction__json_8h.html", "wavefunction__json_8h" ],
    [ "xyz.h", "xyz_8h.html", "xyz_8h" ]
];