#!/usr/bin/env python3
"""Extract Stewart STO-NG fit tables from xtb's src/slater.f90 and emit a
C++ source file (sto_ng_data.cpp) with the same numerical content.

Usage:
    python3 scripts/extract_stong_tables.py [--xtb-src ~/git/xtb] \
        [--out src/xtb/sto_ng_data.cpp]
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path


# Map ityp index to (n, l). 1-based in Fortran, 0-based in C++ output.
ITYP_MAP = [
    (1, 0), (2, 0), (3, 0), (4, 0), (5, 0),
    (2, 1), (3, 1), (4, 1), (5, 1),
    (3, 2), (4, 2), (5, 2),
    (4, 3), (5, 3),
    (5, 4),
]
ASSERT_LABELS = ["1s","2s","3s","4s","5s","2p","3p","4p","5p",
                 "3d","4d","5d","4f","5f","5g"]
NF = 15


def extract_array(text: str, name: str) -> list[float]:
    """Extract the numeric content of a Fortran `parameter :: <name>(...) = reshape([...])`
    array. Returns the values in declaration order (Fortran column-major)."""
    # Match the parameter declaration up to the closing reshape ).
    pat = re.compile(
        rf"parameter\s*::\s*{re.escape(name)}\s*\([^\)]+\)\s*=\s*(?:reshape\(\s*)?\[(.*?)\]",
        re.S,
    )
    m = pat.search(text)
    if not m:
        raise RuntimeError(f"could not find parameter {name}")
    body = m.group(1)
    # strip Fortran continuation markers, comments
    body = re.sub(r"!.*?(?=\n|$)", "", body)
    body = body.replace("&", "")
    body = body.replace("_wp", "")
    nums: list[float] = []
    for tok in re.split(r"[,\s]+", body):
        tok = tok.strip()
        if not tok:
            continue
        try:
            nums.append(float(tok))
        except ValueError:
            raise RuntimeError(f"unparseable token in {name}: {tok!r}")
    return nums


def emit(out: Path, data: dict):
    lines: list[str] = []
    lines += [
        "// Auto-generated by scripts/extract_stong_tables.py from xtb/src/slater.f90.",
        "// Original source: R. F. Stewart, J. Chem. Phys. 52, 431 (1970).",
        "// DOI: 10.1063/1.1672702",
        "// Do not edit by hand — re-run the script.",
        "//",
        "// This file is intended to be #included inside namespace occ::xtb::detail.",
        "",
        "// (n, l) for each ityp (0-based here, was 1-based in Fortran).",
        "constexpr std::array<std::pair<int, int>, 15> ityp_table = {{",
    ]
    for i, (n, l) in enumerate(ITYP_MAP):
        lines.append(f"    {{{n}, {l}}},  // ityp={i}: {ASSERT_LABELS[i]}")
    lines += ["}};", ""]

    # NG=1: only alpha, coeff is implicit 1.0
    a1 = data["pAlpha1"]
    if len(a1) != 15:
        raise RuntimeError(f"pAlpha1 length {len(a1)} != 15")
    lines += [
        "// NG = 1: one primitive per fit. Fortran fixes coeff = 1.",
        "constexpr std::array<double, 15> alpha_ng1 = {",
        "    " + ", ".join(f"{v:.10e}" for v in a1),
        "};",
        "",
    ]

    for ng in (2, 3, 4, 5, 6):
        a = data[f"pAlpha{ng}"]
        c = data[f"pCoeff{ng}"]
        expected = ng * 15
        if len(a) != expected or len(c) != expected:
            raise RuntimeError(
                f"NG={ng}: alpha len {len(a)}, coeff len {len(c)}, expected {expected}"
            )
        lines.append(
            f"// NG = {ng}: stored as [ityp][primitive], so the Fortran column for ityp i"
        )
        lines.append("// ends up as the i-th sub-array here.")
        lines.append(f"constexpr std::array<std::array<double, {ng}>, 15> alpha_ng{ng} = {{{{")
        for i in range(15):
            row = a[i * ng:(i + 1) * ng]
            lines.append("    {" + ", ".join(f"{v:.10e}" for v in row) +
                         f"}},  // {ASSERT_LABELS[i]}")
        lines += ["}};", ""]
        lines.append(f"constexpr std::array<std::array<double, {ng}>, 15> coeff_ng{ng} = {{{{")
        for i in range(15):
            row = c[i * ng:(i + 1) * ng]
            lines.append("    {" + ", ".join(f"{v:.10e}" for v in row) +
                         f"}},  // {ASSERT_LABELS[i]}")
        lines += ["}};", ""]

    a6s = data["pAlpha6s"]; c6s = data["pCoeff6s"]
    a6p = data["pAlpha6p"]; c6p = data["pCoeff6p"]
    for vec, name in [(a6s, "alpha_ng6_6s"), (c6s, "coeff_ng6_6s"),
                      (a6p, "alpha_ng6_6p"), (c6p, "coeff_ng6_6p")]:
        if len(vec) != 6:
            raise RuntimeError(f"{name}: length {len(vec)} != 6")
        lines.append(f"constexpr std::array<double, 6> {name} = {{")
        lines.append("    " + ", ".join(f"{v:.10e}" for v in vec))
        lines += ["};", ""]

    out.write_text("\n".join(lines) + "\n")


def main(argv: list[str]) -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--xtb-src", default=os.path.expanduser("~/git/xtb"))
    repo_root = Path(__file__).resolve().parent.parent
    default_out = repo_root / "src" / "xtb" / "sto_ng_data.inc"
    p.add_argument("--out", default=str(default_out))
    args = p.parse_args(argv)

    src = Path(args.xtb_src) / "src" / "slater.f90"
    if not src.is_file():
        print(f"missing: {src}", file=sys.stderr)
        return 1
    text = src.read_text()

    data = {}
    for name in ["pAlpha1",
                 "pAlpha2", "pCoeff2",
                 "pAlpha3", "pCoeff3",
                 "pAlpha4", "pCoeff4",
                 "pAlpha5", "pCoeff5",
                 "pAlpha6", "pCoeff6",
                 "pAlpha6s", "pCoeff6s",
                 "pAlpha6p", "pCoeff6p"]:
        data[name] = extract_array(text, name)

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    emit(out, data)
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
