set(CPACK_PACKAGE_NAME ${PROJECT_NAME} CACHE STRING "package name")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Open computational chemistry in C++"
    CACHE STRING "package description metadata")

set(CPACK_VERBATIM_VARIABLES YES)
set(CPACK_PACKAGE_INSTALL_DIRECTORY ${CPACK_PACKAGE_NAME})

set(CPACK_PACKAGE_VERSION_MAJOR ${PROJECT_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${PROJECT_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${PROJECT_VERSION_PATCH})

set(CPACK_PACKAGE_CONTACT "peterspackman@fastmail.com")
set(CPACK_PACKAGE_MAINTAINER "Peter Spackman")

include(CPack)
